version: '3.8'

services:
  api:
    build: .
    image: gopportunities-api:latest
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release

  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/